name: Build & Test & Upload Docker Image

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]
  workflow_dispatch:
  schedule:
    # timezone: UTC, https://crontab.cronhub.io/
    - cron: '0 20 * * 0'

env:
  DOCKERHUB_IMAGE: taichunmin/github-actions-nanopb:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker
        run: docker build . -f Dockerfile -t $DOCKERHUB_IMAGE
      - name: Retrieve runner uid and gid
        id: uid-gid
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT
      - name: Test the action
        uses: ./
        env:
          UID: ${{ steps.uid-gid.outputs.uid }}
          GID: ${{ steps.uid-gid.outputs.gid }}
        with:
          command: |
            pwd
            /nanopb/generator/nanopb_generator.py example.proto
            chown $UID:$GID *.pb.h *.pb.c
      - name: Print compiled files
        run: |
          id
          ls -al *.pb.h *.pb.c
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/v1'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        if: github.ref == 'refs/heads/v1'
        run: docker push $DOCKERHUB_IMAGE